services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service

  php81-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
        ENV: dev
        XDEBUG_ENABLED: 1
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    environment:
      APP_DEBUG: "true"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "start_with_request=yes client_port=9007 client_host=host.docker.internal"
      # XDEBUG_CONFIG: "start_with_request=yes client_port=9007 client_host=172.18.0.1"
      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=avtosalon"
      DATABASE_URL: "mysql://user:password@mysql8-service:3306/avtosalon?serverVersion=5.7.27&charset=utf8"

  mysql8-service:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - '8092:3306'
    environment:
      MYSQL_DATABASE: "avtosalon"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
        - mysql-avtosalon-data:/var/lib/mysql:delegated
volumes:
  mysql-avtosalon-data: { }